// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoc-dqyhbEfNQtm_ISPCo06dC4hE9_Jjk',
    appId: '1:1095784014947:web:ea29a30eaf05c55f82c456',
    messagingSenderId: '1095784014947',
    projectId: 'dclicmedical',
    authDomain: 'dclicmedical.firebaseapp.com',
    storageBucket: 'dclicmedical.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDmw1NRymFLVD7gmIV6bxlI81J5JjgDs',
    appId: '1:1095784014947:android:64700276282905a582c456',
    messagingSenderId: '1095784014947',
    projectId: 'dclicmedical',
    storageBucket: 'dclicmedical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxg55bK9NqxaL3x5e9yIYeruWD7NODsFk',
    appId: '1:1095784014947:ios:c283d894fb2d265a82c456',
    messagingSenderId: '1095784014947',
    projectId: 'dclicmedical',
    storageBucket: 'dclicmedical.firebasestorage.app',
    iosBundleId: 'com.example.mediclinique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxg55bK9NqxaL3x5e9yIYeruWD7NODsFk',
    appId: '1:1095784014947:ios:c283d894fb2d265a82c456',
    messagingSenderId: '1095784014947',
    projectId: 'dclicmedical',
    storageBucket: 'dclicmedical.firebasestorage.app',
    iosBundleId: 'com.example.mediclinique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoc-dqyhbEfNQtm_ISPCo06dC4hE9_Jjk',
    appId: '1:1095784014947:web:abf58360238dec7d82c456',
    messagingSenderId: '1095784014947',
    projectId: 'dclicmedical',
    authDomain: 'dclicmedical.firebaseapp.com',
    storageBucket: 'dclicmedical.firebasestorage.app',
  );
}
